// export const ADD_OPTION = "ADD_OPTION";
// export const ADD_POST = "ADD_POST";
export const AUTH_ERROR = "AUTH_ERROR";
// export const CREATE_MESSAGE = "CREATE_MESSAGE";
// export const GET_ERRORS = "GET_ERRORS";
export const GET_POSTS = "GET_POSTS";
export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const INCREMENT_OPTION_COUNT = "INCREMENT_OPTION_COUNT";
export const DECREMENT_OPTION_COUNT = "DECREMENT_OPTION_COUNT";
// export const ADD_REPLY = "ADD_REPLY";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const FOLLOWING = "FOLLOWING";
export const FOLLOW = "FOLLOW";
export const UNFOLLOW = "UNFOLLOW";

// export const POSTTOBEUPDATED = "POSTTOBEUPDATED";
// export const POSTREPORTED = "POSTREPORTED";
// export const STATSPOST = "STATSPOST";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
// export const NOTIFY = "NOTIFY";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const NAVIGATION = "NAVIGATION";
export const SEARCH = "SEARCH";

// types for websocket actions

export const TEMP = "TEMP";
export const GET_COMMENTS = "GET_COMMENTS";
export const SET_COMMENTS_TO_NORMAL = "SET_COMMENTS_TO_NORMAL";

export const INCREMENT_OPTION_COUNT_OF_DETAILED_POST =
  "INCREMENT_OPTION_COUNT_OF_DETAILED_POST";
export const DECREMENT_OPTION_COUNT_OF_DETAILED_POST =
  "DECREMENT_OPTION_COUNT_OF_DETAILED_POST";

export const VOTE_GET_POSTS = "VOTE_GET_POSTS";
export const VOTE_INCREMENT_OPTION_COUNT = "VOTE_INCREMENT_OPTION_COUNT";
export const VOTE_DECREMENT_OPTION_COUNT = "VOTE_DECREMENT_OPTION_COUNT";

export const SET_TIMELINE_TO_NORMAL = "SET_TIMELINE_TO_NORMAL";

export const SET_VOTE_PAGE_TO_NORMAL = "SET_VOTE_PAGE_TO_NORMAL";
